apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-keeper
  namespace: noteapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-keeper
  template:
    metadata:
      labels:
        app: note-keeper
    spec:
      containers:
        - name: app
          image: briankimathi/note-keeper:1.0
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: noteapp-secret

