apiVersion: v1
kind: Secret
metadata:
  name: noteapp-secret
  namespace: noteapp
type: Opaque
stringData:
  MONGODB_DATASOURCE: mongodb://mongodb.database.svc.cluster.local:27017/note_keeper
  MONGODB_USERNAME: mongouser
  MONGODB_PASSWORD: Mongo1234
